{{- if .Values.server.ingress.enabled -}}
{{- $serviceName := include "argo-cd.server.fullname" . -}}
{{- $servicePort := ternary .Values.server.service.servicePortHttps .Values.server.service.servicePortHttp .Values.server.ingress.https -}}
{{- $paths := .Values.server.ingress.paths -}}
{{- $extraPaths := .Values.server.ingress.extraPaths -}}
{{- if semverCompare "<1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: extensions/v1beta1
{{- else if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
{{- if .Values.server.ingress.annotations }}
  annotations:
  {{- range $key, $value := .Values.server.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  name: {{ template "argo-cd.server.fullname" . }}
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
{{- if .Values.server.ingress.labels }}
{{- toYaml .Values.server.ingress.labels | nindent 4 }}
{{- end }}
spec:
  rules:
  {{- if .Values.server.ingress.hosts }}
  {{- range $host := .Values.server.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
  {{- if $extraPaths }}
  {{- toYaml $extraPaths | nindent 10 }}
  {{- end }}
  {{- range $p := $paths }}
          - path: {{ $p }}
            {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
            {{- else }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
            {{- end }}
  {{- end -}}
  {{- end -}}
  {{- else }}
    - http:
        paths:
  {{- if $extraPaths }}
  {{- toYaml $extraPaths | nindent 10 }}
  {{- end }}
  {{- range $p := $paths }}
          - path: {{ $p }}
            {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
            {{- else }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
            {{- end }}
  {{- end -}}
  {{- end -}}
  {{- if .Values.server.ingress.tls }}
  tls:
{{- toYaml .Values.server.ingress.tls | nindent 4 }}
  {{- end -}}
{{- end -}}
